### ISSUE TITLE
improvement need

### ISSUE THREAD

**Issue by rahulsain** [rahulsain3000/birthdaygreet#1]
can anyone write "You're invited to the party! YAY" at the bottom right screen with font size smaller than "Happy Birthday $name"(in sp) this new text should only touch bottom and right side, starting from guideline i.e. situated at centre of the screen.

**Comment by wisetok12680** [comment]
Hey there I would like to contribute

**Comment by rahulsain** [comment]
@wisetok12680 sorry but this issue to assigned to someone else

Any further ui improvement is welcome though

**Comment by wisetok12680** [comment]
Ok
